import { createApp } from 'vue'
import App from './App.vue'
import { router } from './router.ts'

// Doc site styles
import './styles/docs.css'

// CSS
import 'mk-css/styles/variables.css'
import 'mk-css/styles/tokens.css'
import 'mk-css/styles/reset.css'
import '../../src/styles/animations.css'
import '../../src/styles/element-plus.css'
import 'mk-css/button/button.css'
import 'mk-css/input/input.css'
import 'mk-css/card/card.css'
import 'mk-css/tag/tag.css'
import 'mk-css/tabs/tabs.css'
import 'mk-css/table/table.css'
import 'mk-css/avatar/avatar.css'
import 'mk-css/alert/alert.css'
import 'mk-css/progress/progress.css'
import 'mk-css/collapse/collapse.css'
import 'mk-css/empty/empty.css'
import 'mk-css/popover/popover.css'
import 'mk-css/menu/menu.css'
import 'mk-css/breadcrumb/breadcrumb.css'
import 'mk-css/steps/steps.css'
import 'mk-css/switch/switch.css'
import 'mk-css/dialog/dialog.css'
import 'mk-css/drawer/drawer.css'
import 'mk-css/message/message.css'
import 'mk-css/loading/loading.css'
import 'mk-css/layout/row.css'
import 'mk-css/layout/space.css'
import 'mk-css/layout/divider.css'
import 'mk-css/layout/container.css'
import 'mk-css/layout/layout.css'
import 'mk-css/layout/header.css'
import 'mk-css/layout/aside.css'
import 'mk-css/layout/main.css'
import 'mk-css/layout/footer.css'
import 'mk-css/form/select.css'
import 'mk-css/form/checkbox.css'
import 'mk-css/form/radio.css'
import 'mk-css/form/slider.css'

createApp(App).use(router).mount('#app')
